# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'GQLoggerDemo' do
pod 'GQLogger', :path => '../'
pod 'GQSecretImage'
end
target 'GQLoggerDemoTests' do

end
